baseURL: "https://loskutoff.com/"
languageCode: "en-us"
title: "Igor Loskutov"
theme: "ghostwriter"
copyright: "Igor Loskutov"
disqusShortname: firfiblog
googleAnalytics: XXX
pygmentsUseClasses: true
pygmentsCodefences: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: Igor Loskutov
  profile: ""

taxonomies:
  tag: tags

params:
  mainSections:
    - about
  intro: true
  headline: Igor Loskutov
  description: Fullstack Web Developer
  github: "https://github.com/firfi"
  gitlab: ""
  linkedin: "https://linkedin.com/in/igor-loskutov-1636a53b/"
  twitter: ""
  stackoverflow: "https://stackoverflow.com/users/2123547/igor-loskutov"
  facebook: "https://www.facebook.com/igor.loskutoff/"
  email: igor@loskutoff.com
  opengraph: true
  shareTwitter: false
  rss: false
  shareFacebook: false
  shareLinkedIn: false
  dateFormat: "Mon, Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""
  # If you want to use plausible(https://plausible.io) for analytics, add this section
  plausibleAnalytics:
    domain: ""
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL: ""

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: About
      url: /
      weight: 1


